# GET http://localhost:3001/api/persons
# POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jonathan Jung",
    "number": "123-123-123"
}

# GET http://localhost:3001/api/persons
# DELETE http://localhost:3001/api/persons/2 HTTP/1.1